obj-$(CONFIG_PANEL_GENERIC) += panel-generic.o
obj-$(CONFIG_PANEL_SHARP_LS037V7DW01) += panel-sharp-ls037v7dw01.o

obj-$(CONFIG_PANEL_TAAL) += panel-taal.o
obj-$(CONFIG_LCD_4430SDP) += lcd_4430sdp.o
obj-$(CONFIG_PANEL_PICO_DLP) +=  panel-picodlp.o
