/*
*             Texas Instruments OMAP(TM) Platform Firmware
*  (c) Copyright 2009, Texas Instruments Incorporated.  All Rights Reserved.
*
*  Use of this firmware is controlled by the terms and conditions found
*  in the license agreement under which this firmware has been supplied.

* @file ABE_INITxxx_labels.h
*
*
*/
#ifndef __ABE_INITXXX_LABELS_H_
#define __ABE_INITXXX_LABELS_H_

#define Voice_8k_UL_labelID                                 0 
#define Voice_8k_DL_labelID                                 1 
#define ECHO_REF_8K_labelID                                 2 
#define Voice_16k_UL_labelID                                3 
#define Voice_16k_DL_labelID                                4 
#define ECHO_REF_16K_labelID                                5 
#define MM_DL_labelID                                       6 
#define IO_VX_DL_ASRC_labelID                               7 
#define IO_VX_UL_8k_ASRC_labelID                            8 
#define IO_VX_UL_16k_ASRC_labelID                           9 
#define IO_MM_DL_ASRC_labelID                               10 
#define ZERO_labelID                                        11 
#define Z_1_labelID                                         12 
#define Z_M1_labelID                                        13 
#define Dummy_AM_labelID                                    14 
#define Dummy_Regs_labelID                                  15 
#define Gr_1_labelID                                        16 
#define Gr_2_labelID                                        17 
#define Gr_Regs_labelID                                     18 
#define OSR96_2_labelID                                     19 
#define UP_DOWN_48_96_labelID                               20 
#define EQ_96K_labelID                                      21 
#define McPDMout_3_labelID                                  22 
#define DL1_M_labelID                                       23 
#define DL2_M_labelID                                       24 
#define MM_UL2_labelID                                      25 
#define VX_DL_labelID                                       26 
#define Tones_labelID                                       27 
#define DL1_M_G_labelID                                     28 
#define DL2_M_G_labelID                                     29 
#define DLx_M_Regs_labelID                                  30 
#define TC_Regs_labelID                                     31 
#define Echo_M_labelID                                      32 
#define Echo_M_G_labelID                                    33 
#define VX_UL_labelID                                       34 
#define SDT_F_labelID                                       35 
#define SDT_F_data_labelID                                  36 
#define SDT_Coef_labelID                                    37 
#define SDT_Regs_labelID                                    38 
#define SDT_M_labelID                                       39 
#define DL1_labelID                                         40 
#define SDT_M_G_labelID                                     41 
#define DMIC1_labelID                                       42 
#define DMIC1_L_labelID                                     43 
#define DMIC1_R_labelID                                     44 
#define DMIC2_labelID                                       45 
#define DMIC2_L_labelID                                     46 
#define DMIC2_R_labelID                                     47 
#define DMIC3_labelID                                       48 
#define DMIC3_L_labelID                                     49 
#define DMIC3_R_labelID                                     50 
#define BT_UL_labelID                                       51 
#define BT_L_labelID                                        52 
#define BT_R_labelID                                        53 
#define AMIC_labelID                                        54 
#define AMIC_L_labelID                                      55 
#define AMIC_R_labelID                                      56 
#define EANC_FBK_labelID                                    57 
#define EANC_FBK_L_labelID                                  58 
#define EANC_FBK_R_labelID                                  59 
#define EchoRef_L_labelID                                   60 
#define EchoRef_R_labelID                                   61 
#define MM_DL_L_labelID                                     62 
#define MM_DL_R_labelID                                     63 
#define MM_UL_labelID                                       64 
#define AMIC_96_labelID                                     65 
#define DMIC0_96_labelID                                    66 
#define DMIC1_96_labelID                                    67 
#define DMIC2_96_labelID                                    68 
#define DMIC_desc_labelID                                   69 
#define DMIC_eanc_labelID                                   70 
#define DMIC_Regs_labelID                                   71 
#define DMIC_Regs2_labelID                                  72 
#define AMIC_96_F_labelID                                   73 
#define AMIC_96_data_labelID                                74 
#define AMIC_96F_Coefs_labelID                              75 
#define DMIC0_96_F_labelID                                  76 
#define DMIC0_96_data_labelID                               77 
#define DMIC0_96F_Coefs_labelID                             78 
#define DMIC1_96_F_labelID                                  79 
#define DMIC1_96_data_labelID                               80 
#define DMIC2_96_F_labelID                                  81 
#define DMIC2_96_data_labelID                               82 
#define DMIC0_F_labelID                                     83 
#define UL_MIC_48K_labelID                                  84 
#define DMIC0_dec_labelID                                   85 
#define AMIC_EQ_data_labelID                                86 
#define AMIC_EQ_Coefs_labelID                               87 
#define DMIC1_EQ_data_labelID                               88 
#define DMIC1_EQ_Coefs_labelID                              89 
#define DMIC2_EQ_data_labelID                               90 
#define DMIC2_EQ_Coefs_labelID                              91 
#define DMIC3_EQ_data_labelID                               92 
#define DMIC3_EQ_Coefs_labelID                              93 
#define EQ_DL_48K_labelID                                   94 
#define EQ_48K_labelID                                      95 
#define Voice_F_data_labelID                                96 
#define Voice_F_Coefs_labelID                               97 
#define Voice_F_labelID                                     98 
#define SIO_VX_UL_labelID                                   99 
#define SIO_VX_DL_labelID                                   100 
#define SIO_TONES_DL_labelID                                101 
#define VX_DL_data_labelID                                  102 
#define UP_DOWN_8_48_labelID                                103 
#define SIO_MM_DL_labelID                                   104 
#define AMIC_desc_labelID                                   105 
#define AMIC_Regs_labelID                                   106 
#define McPDM_Out1_labelID                                  107 
#define McPDM_Out1_data_labelID                             108 
#define McPDM_Out1_Coefs_labelID                            109 
#define McPDM_Out2_labelID                                  110 
#define McPDM_Out2_data_labelID                             111 
#define McPDM_Out2_Coefs_labelID                            112 
#define McPDM_Out3_labelID                                  113 
#define McPDM_DL_Out1_labelID                               114 
#define McPDM_DL_Regs_labelID                               115 
#define VX_UL_MUX_labelID                                   116 
#define MM_UL2_MUX_labelID                                  117 
#define MM_UL_MUX_labelID                                   118 
#define IO_MM_UL_Regs_labelID                               119 
#define MM_UL_desc_labelID                                  120 
#define MM_UL_FIFO_labelID                                  121 
#define IO_MM_UL2_Regs_labelID                              122 
#define MM_UL2_desc_labelID                                 123 
#define MM_UL2_FIFO_labelID                                 124 
#define XinASRC_DL_VX_labelID                               125 
#define ASRC_DL_VX_Coefs_labelID                            126 
#define ASRC_DL_VX_Alpha_labelID                            127 
#define ASRC_DL_VX_VarsBeta_labelID                         128 
#define ASRC_DL_VX_8k_Regs_labelID                          129 
#define XinASRC_UL_VX_labelID                               130 
#define ASRC_UL_VX_Coefs_labelID                            131 
#define ASRC_UL_VX_Alpha_labelID                            132 
#define ASRC_UL_VX_VarsBeta_labelID                         133 
#define ASRC_UL_VX_8k_Regs_labelID                          134 
#define UL_48_8_DEC_labelID                                 135 
#define UP_DOWN_16_48_labelID                               136 
#define ASRC_DL_VX_16k_Regs_labelID                         137 
#define ASRC_UL_VX_16k_Regs_labelID                         138 
#define UL_48_16_DEC_labelID                                139 
#define XinASRC_DL_MM_labelID                               140 
#define ASRC_DL_MM_Coefs_labelID                            141 
#define ASRC_DL_MM_Alpha_labelID                            142 
#define ASRC_DL_MM_VarsBeta_labelID                         143 
#define ASRC_DL_MM_Regs_labelID                             144 
#define VX_REC_labelID                                      145 
#define VXREC_M_G_labelID                                   146 
#define VXREC_M_Regs_labelID                                147 
#define VX_REC_L_labelID                                    148 
#define VX_REC_R_labelID                                    149 
#define UL_M_G_labelID                                      150 
#define DL2_M_L_labelID                                     151 
#define DL2_M_R_labelID                                     152 
#define DL1_M_data_labelID                                  153 
#define DL1_M_Coefs_labelID                                 154 
#define DL2_M_LR_data_labelID                               155 
#define DL2_M_LR_Coefs_labelID                              156 
#define VX_DL_8_48_LP_COEFS_labelID                         157 
#define VX_DL_8_48_BP_COEFS_labelID                         158 
#define VX_DL_8_48_BP_DATA_labelID                          159 
#define VX_DL_8_48_LP_DATA_labelID                          160 
#define EQ_VX_DL_8K_labelID                                 161 
#define EQ_VX_DL_48K_labelID                                162 
#define UP_48_96_LP0_COEFS_labelID                          163 
#define UP_48_96_LP1_COEFS_labelID                          164 
#define EARP_48_96_LP0_DATA_labelID                         165 
#define EARP_48_96_LP1_DATA_labelID                         166 
#define EQ_48_96_LP0_labelID                                167 
#define EQ_48_96_LP1_labelID                                168 
#define IHF_48_96_LP0_DATA_labelID                          169 
#define IHF_48_96_LP1_DATA_labelID                          170 
#define VX_DL_16_48_HP_COEFS_labelID                        171 
#define VX_DL_16_48_LP_COEFS_labelID                        172 
#define VX_DL_16_48_HP_DATA_labelID                         173 
#define VX_DL_16_48_LP_DATA_labelID                         174 
#define EQ_VX_DL_16K_labelID                                175 
#define VX_UL_48_8_LP_COEFS_labelID                         176 
#define VX_UL_48_8_BP_DATA_labelID                          177 
#define VX_UL_48_8_LP_DATA_labelID                          178 
#define EQ_VX_UL_8K_labelID                                 179 
#define EQ_VX_UL_48K_labelID                                180 
#define VX_UL_8_TEMP_labelID                                181 
#define VX_UL_48_16_LP_COEFS_labelID                        182 
#define VX_UL_48_16_HP_DATA_labelID                         183 
#define VX_UL_48_16_LP_DATA_labelID                         184 
#define EQ_VX_UL_16K_labelID                                185 
#define VX_UL_16_TEMP_labelID                               186 
#define GTarget_labelID                                     187 
#define GCurrent_labelID                                    188 
#define pAPS_iir1_p23_labelID                               189 
#define pAPS_iir1_p45_labelID                               190 
#define APS_IIR_Regs_labelID                                191 
#define pAPS_core_p1_labelID                                192 
#define pAPS_core_p23_labelID                               193 
#define pAPS_core_p45_labelID                               194 
#define pAPS_core_r_labelID                                 195 
#define XinASRC_ECHO_REF_labelID                            196 
#define ASRC_ECHO_REF_Coefs_labelID                         197 
#define ASRC_ECHO_REF_Alpha_labelID                         198 
#define ASRC_ECHO_REF_VarsBeta_labelID                      199 
#define ASRC_ECHO_REF_8k_Regs_labelID                       200 
#define ASRC_ECHO_REF_16k_Regs_labelID                      201 
#define DL2_APS_IIR_p23_labelID                             202 
#define DL2_APS_IIR_p45_labelID                             203 
#define DL2_L_APS_CORE_p23_labelID                          204 
#define DL2_L_APS_CORE_p45_labelID                          205 
#define DL2_R_APS_CORE_p23_labelID                          206 
#define DL2_R_APS_CORE_p45_labelID                          207 
#define DMIC1_Gain_labelID                                  208 
#define DMIC2_Gain_labelID                                  209 
#define DMIC3_Gain_labelID                                  210 
#define AMIC_Gain_labelID                                   211 
#define DL1_Gain_labelID                                    212 
#define DL2_Gain_labelID                                    213 
#define DEFAULT_Gain_labelID                                214 
#define DL1_APS_labelID                                     215 
#define DL2_L_APS_labelID                                   216 
#define DL2_R_APS_labelID                                   217 
#define ECHO_REF_48_16_HP_DATA_labelID                      218 
#define ECHO_REF_48_16_LP_DATA_labelID                      219 
#define ECHO_REF_48_8_BP_DATA_labelID                       220 
#define ECHO_REF_48_8_LP_DATA_labelID                       221 
#define ECHO_REF_DEC_labelID                                222 
#define pEANC_p0_labelID                                    223 
#define pEANC_p1_labelID                                    224 
#define pEANC_p23_labelID                                   225 
#define pEANC_p45_labelID                                   226 
#define pEANC_reg1_labelID                                  227 
#define pEANC_reg2_labelID                                  228 
#define pEANC_reg3_labelID                                  229 
#define pEANC_r_labelID                                     230 
#define DL1_APS_EQ_p23_labelID                              231 
#define DL1_APS_EQ_p45_labelID                              232 
#define DL2_APS_EQ_p23_labelID                              233 
#define DL2_APS_EQ_p45_labelID                              234 

#endif /* _ABE_INITXXXX_LABELS_H_ */
